### ISSUE TITLE
missing input files for KREG example

### ISSUE THREAD

**Issue by ilcpm** [dralgroup/mlatom#25]
i am just learning mlatom, and i found that the input files are missing for the example of KREG at http://mlatom.com/kreg/

the tutorial says to go to XACS to use the example, but in XACS, the folder `/home/mlatom/tutorial` is also missing
![image](https://github.com/user-attachments/assets/2aec598a-38d6-4300-8994-577f187c7053)

![image](https://github.com/user-attachments/assets/8c96fccf-0772-4351-8bcd-1994e5091cf0)

so, where can i get the input files for GREG example? thanks.

by the way, this example looks like being written in "command line" type, can this be written in python type?

**Comment by dralgroup** [comment]
thank you for reporting, we will fix the tutorial ASAP.
Python API is provided for some basic KREG functionalities too (except for pKREG): https://xacs.xmu.edu.cn/docs/mlatom/tutorial_mlp.html

**Comment by Yi-Fan-Hou** [comment]
Hi, we have fixed it. Now all the data files are uploaded on the tutorial website. You can download them and use them to train the models.
